## Lesson 8: Pandas

In [1]:
import numpy as np
import pandas as pd

In [7]:
s1 = pd.Series([1,2,3,4], index = list("abcd"))
s1

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
s1['a']

np.int64(1)

In [4]:
s1[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_9456\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.int64(1)

In [5]:
s1[['a','b']]

a    1
b    2
dtype: int64

In [6]:
s1[:2]

a    1
b    2
dtype: int64

In [8]:
s2 = pd.Series([1,1,1,2,3,3])
s2

0    1
1    1
2    1
3    2
4    3
5    3
dtype: int64

In [9]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
s2.index

RangeIndex(start=0, stop=6, step=1)

In [11]:
s3 = pd.Series({'a':1,'b':4,'c':9})
s3

a    1
b    4
c    9
dtype: int64

In [13]:
df1 = pd.DataFrame({'state': ['Ohio','CA'],
                              'year': [2000, 2010]}, index=list('ab'))
df1

  state  year
a  Ohio  2000
b    CA  2010

In [14]:
df2 = pd.DataFrame({'col1': {'row1': 1,'row2': 2},
                    'col2': {'row1':3, 'row2': 4}})
df2

      col1  col2
row1     1     3
row2     2     4

In [17]:
df3 = pd.DataFrame(data = np.random.rand(3, 2),
                   columns=['foo', 'bar'],
                   index=['a', 'b', 'c'])
df3

        foo       bar
a  0.232302  0.817221
b  0.311573  0.219455
c  0.402996  0.370029

In [18]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [19]:
s1['b']

np.int64(2)

In [20]:
s1[1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_9456\371843902.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[1]

np.int64(2)

In [21]:
s1.loc['a']

np.int64(1)

In [22]:
s1.iloc[0]

np.int64(1)

In [23]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Florida': 170312, 'New York': 141297,
                  'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                 'Florida': 21538187, 'New York': 20201249,
                 'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})

In [24]:
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [25]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [26]:
data.area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [28]:
data['density'] = data['pop']/data['area']
data

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [29]:
data.loc['Texas','density']

np.float64(41.896071655487866)

In [ ]:
data.loc['Texas':'New York','pop']# get all range from start to stop for label index

Texas       29145505
Florida     21538187
New York    20201249
Name: pop, dtype: int64

In [34]:
data

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [35]:
data.iloc[1,2]

np.float64(41.896071655487866)

In [37]:
data.iloc[1:4,1]

Texas       29145505
Florida     21538187
New York    20201249
Name: pop, dtype: int64

In [38]:
np.log(data)

                   area        pop   density
California    12.957411  17.492778  4.535368
Texas         13.452619  17.187811  3.735192
Florida       12.045387  16.885338  4.839951
New York      11.858619  16.821255  4.962636
Pennsylvania  11.689229  16.380668  4.691439

In [39]:
pop_df = data['pop']
area_df = data['area']

In [40]:
pop_df/area_df

California       93.257784
Texas            41.896072
Florida         126.463121
New York        142.970120
Pennsylvania    109.009893
dtype: float64

In [42]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505, 'Florida': 21538187}, name='population')
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [46]:
population

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

In [47]:
population / area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [45]:
population + area

Alaska               NaN
California    39962190.0
Florida              NaN
Texas         29841167.0
dtype: float64

In [48]:
population.add(area, fill_value=0)

Alaska         1723337.0
California    39962190.0
Florida       21538187.0
Texas         29841167.0
dtype: float64

In [49]:
df = pd.DataFrame({
     'A': [1, 2, 3],
     'B': [4, 5, 6],
     'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [51]:
df['D'] = [2,3,4]

In [52]:
df

   A  B  C  D
0  1  4  7  2
1  2  5  8  3
2  3  6  9  4

In [53]:
df.loc['a'] = [1,2,3,4]
df

   A  B  C  D
0  1  4  7  2
1  2  5  8  3
2  3  6  9  4
a  1  2  3  4

In [60]:
df.drop(columns=['D'], inplace=True)

In [61]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
a  1  2  3

In [64]:
df.drop(index='a', inplace=True)

In [65]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [75]:
data = {'Name': ['John', 'Anna', 'Peter', 'Linda', 'James'],
        'Age': [28, 22, np.nan, 32, 25],
        'City': ['New York', 'Paris', 'Berlin', np.nan, 'London'],
        'Salary': [70000, np.nan, np.nan, 85000, np.nan]}
df1 = pd.DataFrame(data)
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [76]:
df1.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False    True
2  False   True  False    True
3  False  False   True   False
4  False  False  False    True

In [77]:
df1.isna().sum()

Name      0
Age       1
City      1
Salary    3
dtype: int64

In [78]:
df1.dropna(how='all')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [79]:
df1.dropna(thresh=3)

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [80]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [81]:
df1.fillna(value=999)

    Name    Age      City   Salary
0   John   28.0  New York  70000.0
1   Anna   22.0     Paris    999.0
2  Peter  999.0    Berlin    999.0
3  Linda   32.0       999  85000.0
4  James   25.0    London    999.0

In [82]:
df1.fillna(value='mean')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris     mean
2  Peter  mean    Berlin     mean
3  Linda  32.0      mean  85000.0
4  James  25.0    London     mean

In [84]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [83]:
df1.fillna(method='bfill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_9456\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris  85000.0
2  Peter  32.0    Berlin  85000.0
3  Linda  32.0    London  85000.0
4  James  25.0    London      NaN

In [86]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [85]:
df1.fillna(method='ffill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_9456\598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris  70000.0
2  Peter  22.0    Berlin  70000.0
3  Linda  32.0    Berlin  85000.0
4  James  25.0    London  85000.0

In [87]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [93]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]
under18= [9267089, 9284094, 4687374, 4318033,5906301, 6879014]
ind = pd.MultiIndex.from_tuples(index, names=('states','years'))
pop = pd.DataFrame({'pop':populations, 'under_18':under18}, index=ind)
pop

                       pop  under_18
states     years
California 2000   33871648   9267089
           2010   37253956   9284094
New York   2000   18976457   4687374
           2010   19378102   4318033
Texas      2000   20851820   5906301
           2010   25145561   6879014

In [96]:
pop.loc[('Texas',2000)]

pop         20851820
under_18     5906301
Name: (Texas, 2000), dtype: int64

In [97]:
pop

                       pop  under_18
states     years
California 2000   33871648   9267089
           2010   37253956   9284094
New York   2000   18976457   4687374
           2010   19378102   4318033
Texas      2000   20851820   5906301
           2010   25145561   6879014

In [98]:
pop.stack()

states      years
California  2000   pop         33871648
                   under_18     9267089
            2010   pop         37253956
                   under_18     9284094
New York    2000   pop         18976457
                   under_18     4687374
            2010   pop         19378102
                   under_18     4318033
Texas       2000   pop         20851820
                   under_18     5906301
            2010   pop         25145561
                   under_18     6879014
dtype: int64

In [103]:
pop

                       pop  under_18
states     years
California 2000   33871648   9267089
           2010   37253956   9284094
New York   2000   18976457   4687374
           2010   19378102   4318033
Texas      2000   20851820   5906301
           2010   25145561   6879014

In [104]:
pop.unstack(level='states')

              pop                       under_18
states California  New York     Texas California New York    Texas
years
2000     33871648  18976457  20851820    9267089  4687374  5906301
2010     37253956  19378102  25145561    9284094  4318033  6879014

In [105]:
url = 'https://raw.githubusercontent.com/ntlong-NEU/DSEB65B-DataPre-Visual/refs/heads/main/Data/OnlineRetail.csv'
df_retail = pd.read_csv(url)

In [108]:
df_retail.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom

In [109]:
df_retail.tail(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
203419,558637,22033,BOTANICAL ROSE GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203420,558637,22029,SPACEBOY BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203421,558637,22024,RAINY LADIES BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom