## Lesson 8: Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4], index = list("abcd"))
s1

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
s1['a']

np.int64(1)

In [4]:
s1[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18144\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.int64(1)

In [5]:
s1[['a','b']]

a    1
b    2
dtype: int64

In [6]:
s1[:2]

a    1
b    2
dtype: int64

In [7]:
s2 = pd.Series([1,1,1,2,3,3])
s2

0    1
1    1
2    1
3    2
4    3
5    3
dtype: int64

In [8]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
s2.index

RangeIndex(start=0, stop=6, step=1)

In [10]:
s3 = pd.Series({'a':1,'b':4,'c':9})
s3

a    1
b    4
c    9
dtype: int64

In [11]:
df1 = pd.DataFrame({'state': ['Ohio','CA'],
                              'year': [2000, 2010]}, index=list('ab'))
df1

  state  year
a  Ohio  2000
b    CA  2010

In [12]:
df2 = pd.DataFrame({'col1': {'row1': 1,'row2': 2},
                    'col2': {'row1':3, 'row2': 4}})
df2

      col1  col2
row1     1     3
row2     2     4

In [13]:
df3 = pd.DataFrame(data = np.random.rand(3, 2),
                   columns=['foo', 'bar'],
                   index=['a', 'b', 'c'])
df3

        foo       bar
a  0.271043  0.550721
b  0.796287  0.649921
c  0.871450  0.622132

In [14]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
s1['b']

np.int64(2)

In [16]:
s1[1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18144\371843902.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[1]

np.int64(2)

In [17]:
s1.loc['a']

np.int64(1)

In [18]:
s1.iloc[0]

np.int64(1)

In [19]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Florida': 170312, 'New York': 141297,
                  'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                 'Florida': 21538187, 'New York': 20201249,
                 'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})

In [20]:
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [21]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [22]:
data.area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [23]:
data['density'] = data['pop']/data['area']
data

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [24]:
data.loc['Texas','density']

np.float64(41.896071655487866)

In [25]:
data.loc['Texas':'New York','pop']# get all range from start to stop for label index

Texas       29145505
Florida     21538187
New York    20201249
Name: pop, dtype: int64

In [26]:
data

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [27]:
data.iloc[1,2]

np.float64(41.896071655487866)

In [28]:
data.iloc[1:4,1]

Texas       29145505
Florida     21538187
New York    20201249
Name: pop, dtype: int64

In [29]:
np.log(data)

                   area        pop   density
California    12.957411  17.492778  4.535368
Texas         13.452619  17.187811  3.735192
Florida       12.045387  16.885338  4.839951
New York      11.858619  16.821255  4.962636
Pennsylvania  11.689229  16.380668  4.691439

In [30]:
pop_df = data['pop']
area_df = data['area']

In [31]:
pop_df/area_df

California       93.257784
Texas            41.896072
Florida         126.463121
New York        142.970120
Pennsylvania    109.009893
dtype: float64

In [32]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505, 'Florida': 21538187}, name='population')
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [33]:
population

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64

In [34]:
population / area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [35]:
population + area

Alaska               NaN
California    39962190.0
Florida              NaN
Texas         29841167.0
dtype: float64

In [36]:
population.add(area, fill_value=0)

Alaska         1723337.0
California    39962190.0
Florida       21538187.0
Texas         29841167.0
dtype: float64

In [37]:
df = pd.DataFrame({
     'A': [1, 2, 3],
     'B': [4, 5, 6],
     'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [38]:
df['D'] = [2,3,4]

In [39]:
df

   A  B  C  D
0  1  4  7  2
1  2  5  8  3
2  3  6  9  4

In [40]:
df.loc['a'] = [1,2,3,4]
df

   A  B  C  D
0  1  4  7  2
1  2  5  8  3
2  3  6  9  4
a  1  2  3  4

In [41]:
df.drop(columns=['D'], inplace=True)

In [42]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
a  1  2  3

In [43]:
df.drop(index='a', inplace=True)

In [44]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [45]:
data = {'Name': ['John', 'Anna', 'Peter', 'Linda', 'James'],
        'Age': [28, 22, np.nan, 32, 25],
        'City': ['New York', 'Paris', 'Berlin', np.nan, 'London'],
        'Salary': [70000, np.nan, np.nan, 85000, np.nan]}
df1 = pd.DataFrame(data)
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [46]:
df1.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False    True
2  False   True  False    True
3  False  False   True   False
4  False  False  False    True

In [47]:
df1.isna().sum()

Name      0
Age       1
City      1
Salary    3
dtype: int64

In [48]:
df1.dropna(how='all')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [49]:
df1.dropna(thresh=3)

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [50]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [51]:
df1.fillna(value=999)

    Name    Age      City   Salary
0   John   28.0  New York  70000.0
1   Anna   22.0     Paris    999.0
2  Peter  999.0    Berlin    999.0
3  Linda   32.0       999  85000.0
4  James   25.0    London    999.0

In [52]:
df1.fillna(value='mean')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris     mean
2  Peter  mean    Berlin     mean
3  Linda  32.0      mean  85000.0
4  James  25.0    London     mean

In [53]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [54]:
df1.fillna(method='bfill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_18144\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris  85000.0
2  Peter  32.0    Berlin  85000.0
3  Linda  32.0    London  85000.0
4  James  25.0    London      NaN

In [55]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [56]:
df1.fillna(method='ffill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_18144\598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris  70000.0
2  Peter  22.0    Berlin  70000.0
3  Linda  32.0    Berlin  85000.0
4  James  25.0    London  85000.0

In [57]:
df1

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin      NaN
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [58]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]
under18= [9267089, 9284094, 4687374, 4318033,5906301, 6879014]
ind = pd.MultiIndex.from_tuples(index, names=('states','years'))
pop = pd.DataFrame({'pop':populations, 'under_18':under18}, index=ind)
pop

                       pop  under_18
states     years
California 2000   33871648   9267089
           2010   37253956   9284094
New York   2000   18976457   4687374
           2010   19378102   4318033
Texas      2000   20851820   5906301
           2010   25145561   6879014

In [59]:
pop.loc[('Texas',2000)]

pop         20851820
under_18     5906301
Name: (Texas, 2000), dtype: int64

In [60]:
pop

                       pop  under_18
states     years
California 2000   33871648   9267089
           2010   37253956   9284094
New York   2000   18976457   4687374
           2010   19378102   4318033
Texas      2000   20851820   5906301
           2010   25145561   6879014

In [61]:
pop.stack()

states      years
California  2000   pop         33871648
                   under_18     9267089
            2010   pop         37253956
                   under_18     9284094
New York    2000   pop         18976457
                   under_18     4687374
            2010   pop         19378102
                   under_18     4318033
Texas       2000   pop         20851820
                   under_18     5906301
            2010   pop         25145561
                   under_18     6879014
dtype: int64

In [62]:
pop

                       pop  under_18
states     years
California 2000   33871648   9267089
           2010   37253956   9284094
New York   2000   18976457   4687374
           2010   19378102   4318033
Texas      2000   20851820   5906301
           2010   25145561   6879014

In [63]:
pop.unstack(level='states')

              pop                       under_18
states California  New York     Texas California New York    Texas
years
2000     33871648  18976457  20851820    9267089  4687374  5906301
2010     37253956  19378102  25145561    9284094  4318033  6879014

In [64]:
url = 'https://raw.githubusercontent.com/ntlong-NEU/DSEB65B-DataPre-Visual/refs/heads/main/Data/OnlineRetail.csv'
df_retail = pd.read_csv(url)

KeyboardInterrupt:

In [ ]:
df_retail.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom

In [ ]:
df_retail.tail(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
203419,558637,22033,BOTANICAL ROSE GREETING CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203420,558637,22029,SPACEBOY BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom
203421,558637,22024,RAINY LADIES BIRTHDAY CARD,12,2011-06-30 20:08:00,0.42,17891.0,United Kingdom

In [ ]:
df_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [ ]:
df_retail.duplicated().sum()

np.int64(1512)

In [ ]:
df_clean = df_retail.drop_duplicates()
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201910 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    201910 non-null  object
 1   StockCode    201910 non-null  object
 2   Description  201111 non-null  object
 3   Quantity     201910 non-null  int64
 4   InvoiceDate  201910 non-null  object
 5   UnitPrice    201910 non-null  float64
 6   CustomerID   148549 non-null  float64
 7   Country      201910 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 13.9+ MB

In [ ]:
df_clean.describe()

            Quantity      UnitPrice     CustomerID
count  201910.000000  201910.000000  148549.000000
mean        9.636244       4.895271   15235.117800
std       241.818514     114.111181    1718.264132
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13777.000000
50%         3.000000       2.100000   15059.000000
75%        10.000000       4.130000   16771.000000
max     74215.000000   38970.000000   18287.000000

In [65]:
import numpy as np
import pandas as pd

In [66]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])
print(df1)
print(df2)

  letter  number
0      a       1
1      b       2
  letter  number animal
0      c       3    cat
1      d       4    dog

In [67]:
pd.concat([df1,df2])

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [68]:
pd.concat([df1,df2], join= 'inner')

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [69]:
pd.concat([df1,df2], axis= 1)

  letter  number letter  number animal
0      a       1      c       3    cat
1      b       2      d       4    dog

In [70]:
pd.concat([df1,df2], axis= 1, join='inner')

  letter  number letter  number animal
0      a       1      c       3    cat
1      b       2      d       4    dog

In [71]:
url1 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
url2 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'
url3 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'

pop = pd.read_csv(url1)
areas = pd.read_csv(url2)
abbrevs = pd.read_csv(url3)

In [72]:
pop.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [73]:
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [74]:
abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [79]:
df_pop = pd.merge(pd.merge(areas, abbrevs),pop, left_on= 'abbreviation', right_on='state/region')[['state','area (sq. mi)','ages','year','population']]

In [80]:
df_pop.head()

     state  area (sq. mi)     ages  year  population
0  Alabama          52423  under18  2012   1117489.0
1  Alabama          52423    total  2012   4817528.0
2  Alabama          52423  under18  2010   1130966.0
3  Alabama          52423    total  2010   4785570.0
4  Alabama          52423  under18  2011   1125763.0

In [81]:
df_pop['density'] = df_pop['population']/df_pop['area (sq. mi)']
df_pop.head()

     state  area (sq. mi)     ages  year  population    density
0  Alabama          52423  under18  2012   1117489.0  21.316769
1  Alabama          52423    total  2012   4817528.0  91.897221
2  Alabama          52423  under18  2010   1130966.0  21.573851
3  Alabama          52423    total  2010   4785570.0  91.287603
4  Alabama          52423  under18  2011   1125763.0  21.474601

In [83]:
den_2010 = df_pop[(df_pop['ages']=='total')&(df_pop['year']==2010)]
den_2010.head()

          state  area (sq. mi)   ages  year  population     density
3       Alabama          52423  total  2010   4785570.0   91.287603
91       Alaska         656425  total  2010    713868.0    1.087509
101     Arizona         114006  total  2010   6408790.0   56.214497
189    Arkansas          53182  total  2010   2922280.0   54.948667
197  California         163707  total  2010  37333601.0  228.051342

In [84]:
den_2010.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 3 to 2405
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          51 non-null     object
 1   area (sq. mi)  51 non-null     int64
 2   ages           51 non-null     object
 3   year           51 non-null     int64
 4   population     51 non-null     float64
 5   density        51 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 2.8+ KB

In [89]:
den_2010['rank'] = den_2010['density'].rank(ascending= False)
den_2010.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_18144\377003663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  den_2010['rank'] = den_2010['density'].rank(ascending= False)

          state  area (sq. mi)   ages  year  population     density  rank
3       Alabama          52423  total  2010   4785570.0   91.287603  26.0
91       Alaska         656425  total  2010    713868.0    1.087509  51.0
101     Arizona         114006  total  2010   6408790.0   56.214497  34.0
189    Arkansas          53182  total  2010   2922280.0   54.948667  35.0
197  California         163707  total  2010  37333601.0  228.051342  12.0

In [90]:
den_2010.sort_values(by='rank')

,state,area (sq. mi),ages,year,population,density,rank
2405,District of Columbia,68,total,2010,605125.0,8898.897059,1.0
1397,New Jersey,8722,total,2010,8802707.0,1009.253268,2.0
1866,Rhode Island,1545,total,2010,1052669.0,681.339159,3.0
293,Connecticut,5544,total,2010,3579210.0,645.600649,4.0
1002,Massachusetts,10555,total,2010,6563263.0,621.815538,5.0
917,Maryland,12407,total,2010,5787193.0,466.445797,6.0
379,Delaware,1954,total,2010,899711.0,460.445752,7.0
1493,New York,54475,total,2010,19398228.0,356.094135,8.0
427,Florida,65758,total,2010,18846054.0,286.597129,9.0
1781,Pennsylvania,46058,total,2010,12710472.0,275.966651,10.0
1674,Ohio,44828,total,2010,11545435.0,257.549634,11.0
197,California,163707,total,2010,37333601.0,228.051342,12.0
618,Illinois,57918,total,2010,12839695.0,221.687472,13.0
2165,Virginia,42769,total,2010,8024417.0,187.622273,14.0
629,Indiana,36420,total,2010,6489965.0,178.197831,15.0
1578,North Carolina,53821,total,2010,9559533.0,177.617157,16.0
437,Georgia,59441,total,2010,9713248.0,163.409902,17.0
1973,Tennessee,42146,total,2010,6356683.0,150.825298,18.0
1877,South Carolina,32007,total,2010,4636361.0,144.854594,19.0
1386,New Hampshire,9351,total,2010,1316614.0,140.799273,20.0
522,Hawaii,10932,total,2010,1363731.0,124.746707,21.0
810,Kentucky,40411,total,2010,4347698.0,107.586994,22.0
1013,Michigan,96810,total,2010,9876149.0,102.015794,23.0
2250,Washington,71303,total,2010,6742256.0,94.557817,24.0
2058,Texas,268601,total,2010,25245178.0,93.987655,25.0
3,Alabama,52423,total,2010,4785570.0,91.287603,26.0
821,Louisiana,51843,total,2010,4545392.0,87.676099,27.0
2346,Wisconsin,65503,total,2010,5689060.0,86.851900,28.0
1194,Missouri,69709,total,2010,5996063.0,86.015622,29.0
2261,West Virginia,24231,total,2010,1854146.0,76.519582,30.0
2154,Vermont,9615,total,2010,625793.0,65.085075,31.0
1109,Mississippi,48434,total,2010,2970047.0,61.321530,32.0
1098,Minnesota,86943,total,2010,5310337.0,61.078373,33.0
101,Arizona,114006,total,2010,6408790.0,56.214497,34.0
189,Arkansas,53182,total,2010,2922280.0,54.948667,35.0
714,Iowa,56276,total,2010,3050314.0,54.202751,36.0
1685,Oklahoma,69903,total,2010,3759263.0,53.778278,37.0
283,Colorado,104100,total,2010,5048196.0,48.493718,38.0
1770,Oregon,98386,total,2010,3837208.0,39.001565,39.0
906,Maine,35387,total,2010,1327366.0,37.509990,40.0
725,Kansas,82282,total,2010,2858910.0,34.745266,41.0
2069,Utah,84904,total,2010,2774424.0,32.677188,42.0
1301,Nevada,110567,total,2010,2703230.0,24.448796,43.0
1290,Nebraska,77358,total,2010,1829838.0,23.654153,44.0
533,Idaho,83574,total,2010,1570718.0,18.794338,45.0
1482,New Mexico,121593,total,2010,2064982.0,16.982737,46.0
1962,South Dakota,77121,total,2010,816211.0,10.583512,47.0
1589,North Dakota,70704,total,2010,674344.0,9.537565,48.0
1205,Montana,147046,total,2010,990527.0,6.736171,49.0
2357,Wyoming,97818,total,2010,564222.0,5.768079,50.0
91,Alaska,656425,total,2010,713868.0,1.087509,51.0